CREATE TABLE PERSON (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Sex VARCHAR(10)
);

CREATE TABLE PERSON_PHONE (
    PHONE VARCHAR(20),
    ID INT,
    FOREIGN KEY (ID) REFERENCES PERSON(ID)
);

CREATE TABLE BED (
    BedID INT AUTO_INCREMENT PRIMARY KEY,
    BedType VARCHAR(50)
);

CREATE TABLE BED_BOOKING (
    BedID INT,
    Name VARCHAR(100),
    Email VARCHAR(100),
    Contact VARCHAR(50),
    BookingDate DATE,
    PatientID INT,
    FOREIGN KEY (BedID) REFERENCES BED(BedID),
    FOREIGN KEY (PatientID) REFERENCES PERSON(ID)
);

CREATE TABLE BILL_METHOD (
    BILL_METHOD_ID INT AUTO_INCREMENT PRIMARY KEY,
    PaymentMethod VARCHAR(50)
);

CREATE TABLE BILL (
    BILL_ID INT AUTO_INCREMENT PRIMARY KEY,
    Amount DECIMAL(10, 2),
    IssueDate DATE,
    PaymentDate DATE,
    PaymentStatus VARCHAR(50),
    Vat DECIMAL(10, 2),
    PatientID INT,
    BILL_METHOD_ID INT,
    FOREIGN KEY (PatientID) REFERENCES PERSON(ID),
    FOREIGN KEY (BILL_METHOD_ID) REFERENCES BILL_METHOD(BILL_METHOD_ID)
);

CREATE TABLE PATIENT (
    PatientID INT,
    Occupation VARCHAR(50),
    BloodGroup VARCHAR(10),
    MedicineID INT,
    FOREIGN KEY (PatientID) REFERENCES PERSON(ID)
);

CREATE TABLE PHYSICIAN (
    PhysicianID INT AUTO_INCREMENT PRIMARY KEY,
    Specialization VARCHAR(100),
    WorkHour VARCHAR(50)
);

CREATE TABLE PHYSICIAN_CERTIFICATE (
    Certification VARCHAR(100),
    PhysicianID INT,
    FOREIGN KEY (PhysicianID) REFERENCES PHYSICIAN(PhysicianID)
);

CREATE TABLE MEDICAL_HISTORY (
    MH_ID INT AUTO_INCREMENT PRIMARY KEY,
    DateOfRecord DATE,
    MedicalNote TEXT,
    PatientID INT,
    FOREIGN KEY (PatientID) REFERENCES PERSON(ID)
);

CREATE TABLE MEDICATION_HISTORY (
    Medication VARCHAR(100),
    MH_ID INT,
    FOREIGN KEY (MH_ID) REFERENCES MEDICAL_HISTORY(MH_ID)
);

CREATE TABLE DIAGNOSIS_HISTORY (
    Diagnose VARCHAR(100),
    MH_ID INT,
    FOREIGN KEY (MH_ID) REFERENCES MEDICAL_HISTORY(MH_ID)
);

CREATE TABLE SURGERY_HISTORY (
    MH_ID INT,
    Surgery VARCHAR(100),
    FOREIGN KEY (MH_ID) REFERENCES MEDICAL_HISTORY(MH_ID)
);

CREATE TABLE MEDICINE (
    MedicineID INT AUTO_INCREMENT PRIMARY KEY,
    Dosage VARCHAR(50),
    Frequency VARCHAR(50),
    Duration VARCHAR(50)
);

CREATE TABLE PRESCRIPTION (
    PrescriptionID INT AUTO_INCREMENT PRIMARY KEY,
    Diagnosis VARCHAR(100),
    PhysicianID INT,
    MH_ID INT,
    PatientID INT,
    FOREIGN KEY (PhysicianID) REFERENCES PHYSICIAN(PhysicianID),
    FOREIGN KEY (MH_ID) REFERENCES MEDICAL_HISTORY(MH_ID),
    FOREIGN KEY (PatientID) REFERENCES PERSON(ID)
);

CREATE TABLE PRESCRIPTION_SYMPTOM (
    Symptoms VARCHAR(100),
    PrescriptionID INT,
    FOREIGN KEY (PrescriptionID) REFERENCES PRESCRIPTION(PrescriptionID)
);

CREATE TABLE MEDICINE_PRESCRIBED (
    Medicine VARCHAR(100),
    PrescriptionID INT,
    FOREIGN KEY (PrescriptionID) REFERENCES PRESCRIPTION(PrescriptionID)
);

CREATE TABLE APPOINTMENT (
    AppointmentID INT AUTO_INCREMENT PRIMARY KEY,
    AppointmentDate DATE,
    AppointmentTime TIME,
    Status VARCHAR(50),
    Cost DECIMAL(10, 2),
    PatientID INT,
    PhysicianID INT,
    FOREIGN KEY (PatientID) REFERENCES PERSON(ID),
    FOREIGN KEY (PhysicianID) REFERENCES PHYSICIAN(PhysicianID)
);

CREATE TABLE MEDICATION (
    MedicineID INT AUTO_INCREMENT PRIMARY KEY,
    MedicationName VARCHAR(100)
);

CREATE TABLE DIAGNOSIS (
    DiagnosisID INT AUTO_INCREMENT PRIMARY KEY,
    DiagnosisDate DATE,
    Description TEXT,
    DiagnosisName VARCHAR(100),
    PrescriptionID INT,
    FOREIGN KEY (PrescriptionID) REFERENCES PRESCRIPTION(PrescriptionID)
);

CREATE TABLE DIET (
    DietID INT AUTO_INCREMENT PRIMARY KEY,
    DietName VARCHAR(100),
    Description TEXT,
    PrescriptionID INT,
    FOREIGN KEY (PrescriptionID) REFERENCES PRESCRIPTION(PrescriptionID)
);

CREATE TABLE DIET_FOOD (
    DietID INT,
    Food VARCHAR(100),
    FOREIGN KEY (DietID) REFERENCES DIET(DietID)
);

CREATE TABLE DIET_CONTENT (
    DietID INT,
    Content VARCHAR(100),
    FOREIGN KEY (DietID) REFERENCES DIET(DietID)
);

CREATE TABLE DIAGNOSIS_REPORT (
    DiagnosisReportID INT AUTO_INCREMENT PRIMARY KEY,
    Date DATE,
    Status VARCHAR(50),
    DiagnosisID INT,
    PhysicianID INT,
    FOREIGN KEY (DiagnosisID) REFERENCES DIAGNOSIS(DiagnosisID),
    FOREIGN KEY (PhysicianID) REFERENCES PHYSICIAN(PhysicianID)
);

CREATE TABLE LAB (
    DiagnosisReportID INT,
    LabResult TEXT,
    FOREIGN KEY (DiagnosisReportID) REFERENCES DIAGNOSIS_REPORT(DiagnosisReportID)
);
